### ISSUE TITLE
What's the best way to use ppp:main?

### ISSUE THREAD

**Issue by lthms** [fisxoj/postmodern-passenger-pigeon#5]
Hi,

I am relatively new to common lisp, and something I always have trouble figuring out is how to build executables.

Turns out, ppp needs (as far as I understand how things works) `ppp:main` to be called from a dedicated executables, to be able to parse command line arguments.

To be honest, I have no idea how to do that easily. Any advice?

Thanks!

**Comment by lthms** [comment]
Digging a bit more into the matter, I have finally found something that works:

```common-lisp
(ql:quickload :postmodern-passenger-pigeon)
(setf uiop:*image-entry-point* 'ppp:main)
(uiop:dump-image "pigeon" :executable t)
```

**Comment by vindarel** [comment]
Hello, we at the Cookbook hope this answers your questions: https://lispcookbook.github.io/cl-cookbook/scripting.html (nice finding though)

**Comment by lthms** [comment]
Thanks for the link! It has been helpful.

**Comment by fisxoj** [comment]
Hi @vindarel and @lthms! I'm sorry I didn't see this sooner, I'm quite late to the party now.

Is there something more I can add to documentation that would have helped you here?  I'd be open to adding something about building ppp as an executable, if that's a way you're using it, I'm just a little strapped for time so I'd love to know that someone would use it to help me prioritize.

I'm going to close since I think @vindarel gave you the answer you needed, but please feel free to reopen if you think there's something I could do or just make clearer and thanks for trying out my work!
